set(LHAPDF_FOUND NOTFOUND)

SET(LHAPDF_ROOT_DIR "" CACHE FILEPATH "description")
FIND_PATH(LHAPDF_INCLUDE_DIR LHAPDF/LHAPDF.h HINTS ${LHAPDF_ROOT_DIR}/include)
FIND_LIBRARY(LHAPDF_LIBRARY LHAPDF HINTS ${LHAPDF_ROOT_DIR}/lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LHAPDF DEFAULT_MSG LHAPDF_LIBRARY LHAPDF_INCLUDE_DIR)
IF(LHAPDF_FOUND)
        SET(LHAPDF_LIBRARIES ${LHAPDF_LIBRARY})
        SET(LHAPDF_INCLUDE_DIRS ${LHAPDF_INCLUDE_DIR})
ELSE(LHAPDF_FOUND)
        SET(LHAPDF_LIBRARIES NOTFOUND)
        SET(LHAPDF_INCLUDE_DIRS NOTFOUND)
ENDIF(LHAPDF_FOUND)

MARK_AS_ADVANCED(LHAPDF_INCLUDE_DIRS LHAPDF_LIBRARIES)

